### ISSUE TITLE
Migration step fails but shows as successful run in Action UI

### ISSUE THREAD

**Issue by sterlingwes** [cloudflare/wildebeest#343]
Was getting "timeline cannot be loaded, please try again" when I tried to load the site after deploy and couldn't figure out why. Turns out the database was empty! Even though the deploy job seemed to finish fine first time around:

<img width="1103" alt="Screenshot 2023-02-25 at 6 09 14 PM" src="https://user-images.githubusercontent.com/1047502/221383740-9b4959a8-2b77-4a17-8368-3582b48aaab3.png">

<img width="906" alt="Screenshot 2023-02-25 at 6 09 24 PM" src="https://user-images.githubusercontent.com/1047502/221383742-f565ffb3-6790-4f67-a717-e1a1bc96a65a.png">

Looks like the d1 migrations command doesn't exit with a non-zero?

The fix for me was to pull out the migration steps in a separate workflow so I could run it again (https://github.com/cloudflare/wildebeest/compare/main...sterlingwes:wildebeest:fix/migration)

**Comment by xtuc** [comment]
Intermittent D1 error, should fix itself after a rerun (which is what your change did).

**Comment by sterlingwes** [comment]
@xtuc the issue is that the error doesn't manifest as a GH action run failure, which is the actual issue here

**Comment by sterlingwes** [comment]
@xtuc this is still an issue

should i open this on the wrangler repo? unclear to me where this exit code is getting swallowed
